### ISSUE TITLE
method to capture screen from the scene

### ISSUE THREAD

**Issue by mostaphaRoudsari** [design-generator/design-generator.github.io#7]

**Comment by alfarok** [comment]
@mostaphaRoudsari @mdahlhausen @ksobon  I was able to capture the screen using [this](http://learningthreejs.com/blog/2011/09/03/screenshot-in-javascript/) method.  The "p" key is binded to the print screen event which opens the capture in a new window.  We can probably build off this logic to fit our needs.

**Comment by mostaphaRoudsari** [comment]
Nice! works like a charm.

**Comment by alfarok** [comment]
@mostaphaRoudsari Might be getting a little ahead on this one, but wanted to test out the vertex coloring :) keep me posted on the next steps required on the visual side
![vertex_coloring_example](https://cloud.githubusercontent.com/assets/13341935/21584378/09e264aa-d074-11e6-8891-0566712ec57d.JPG)

**Comment by mostaphaRoudsari** [comment]
@alfarok beautiful! I'm waiting for someone from the analytic team to give me a valid list of inputs  that matches the outputs. Then I will be able to give you the results of the analysis for each variation. Thanks for pushing this forward.
